/**
 * MKL (https://mkl.ba).
 *
 * @link https://github.com/mkl source repository
 *
 * @copyright Copyright (c) 2024. MKL (https://mkl.ba)
 *
 * @license https://www.elastic.co/licensing/elastic-license
 */

import '@resources/css/app.css';

import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import { ConfigProvider } from 'antd';
import { getServerSession } from 'next-auth';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, unstable_setRequestLocale } from 'next-intl/server';
import { ReactNode } from 'react';
import { Toaster } from 'react-hot-toast';

import { SessionProvider } from '@components/index';

import { useTheme } from '@hooks/index';

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: { locale: string };
}>) => {
  unstable_setRequestLocale(params.locale);

  const theme = useTheme();

  const messages = await getMessages();

  const session = await getServerSession();

  return (
    <html lang={params.locale}>
      <body className={poppins.className}>
        <ConfigProvider wave={{ disabled: true }} theme={theme}>
          <NextIntlClientProvider messages={messages}>
            <SessionProvider session={session}>{children}</SessionProvider>
            <Toaster position="top-center" />
          </NextIntlClientProvider>
        </ConfigProvider>
      </body>
    </html>
  );
};

export default RootLayout;
